[package]
name = "dotenv-linter"
version = "0.1.0"
authors = ["Mikhail Grachev <work@mgrachev.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
